# Generated by Django 6.0 on 2026-03-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="newsletter_opt_in",
            field=models.BooleanField(default=False),
        ),
    ]
