# Generated by Django 6.0 on 2026-02-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movies",
            "0003_movie_backdrop_path_movie_overview_movie_poster_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="original_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="popularity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_countries",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_average",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
