# Generated by Django 6.0 on 2026-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="watch_providers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
