# Generated by Django 6.0 on 2026-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_movie_watch_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_credits",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="movie",
            name="similar",
            field=models.JSONField(default=list),
        ),
    ]
