name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            set -e
            cd /var/www/whichmovie_app

            git pull origin main

            /root/.local/bin/uv sync --no-dev

            /root/.local/bin/uv run python manage.py migrate --noinput
            /root/.local/bin/uv run python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn
            sudo systemctl restart dramatiq
            sudo systemctl restart dramatiq-crontab
